export default {
    "login": "SantRuan",
    "id": 73765377,
    "node_id": "MDQ6VXNlcjczNzY1Mzc3",
    "avatar_url": "https://avatars.githubusercontent.com/u/73765377?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/SantRuan",
    "html_url": "https://github.com/SantRuan",
    "followers_url": "https://api.github.com/users/SantRuan/followers",
    "following_url": "https://api.github.com/users/SantRuan/following{/other_user}",
    "gists_url": "https://api.github.com/users/SantRuan/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/SantRuan/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/SantRuan/subscriptions",
    "organizations_url": "https://api.github.com/users/SantRuan/orgs",
    "repos_url": "https://api.github.com/users/SantRuan/repos",
    "events_url": "https://api.github.com/users/SantRuan/events{/privacy}",
    "received_events_url": "https://api.github.com/users/SantRuan/received_events",
    "type": "User",
    "site_admin": false,
    "name": null,
    "company": null,
    "blog": "",
    "location": null,
    "email": null,
    "hireable": null,
    "bio": "Silence please, I'm trying to learn.",
    "twitter_username": null,
    "public_repos": 13,
    "public_gists": 0,
    "followers": 1,
    "following": 1,
    "created_at": "2020-11-01T01:51:43Z",
    "updated_at": "2021-06-25T14:18:32Z"
  
};
